version: '3.8'

services:
  backend:
    build: .
    container_name: presentation_backend
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - db_volume:/app/db_data
    networks:
      - shared-network

  bot:
    build: .
    container_name: presentation_bot
    depends_on:
      - backend
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app
      - db_volume:/app/db_data
    networks:
      - shared-network
    command: sh -c "python -m bot.main"


networks:
  shared-network:
    external: true