version: '3.8'

services:
  backend:
    build: .
    container_name: presentation_con
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    networks:
      - app_network

volumes:
  media_volume:
